---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/chiranthajjamane/Desktop/Cu Denver/Github Push Notes/DSA in C++/Stack'
relocations:
  - { offset: 0x514D, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x16C13, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offset: 0x52E5, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x348, symBinAddr: 0x100003C10, symSize: 0x94 }
  - { offset: 0x5326, size: 0x8, addend: 0x0, symName: __Z6isFull5Stack, symObjAddr: 0x318, symBinAddr: 0x100003BE0, symSize: 0x30 }
  - { offset: 0x5358, size: 0x8, addend: 0x0, symName: __Z7isEmpty5Stack, symObjAddr: 0x2F0, symBinAddr: 0x100003BB8, symSize: 0x28 }
  - { offset: 0x538A, size: 0x8, addend: 0x0, symName: __Z8stackTop5Stack, symObjAddr: 0x298, symBinAddr: 0x100003B60, symSize: 0x58 }
  - { offset: 0x53CB, size: 0x8, addend: 0x0, symName: __Z4peek5Stacki, symObjAddr: 0x250, symBinAddr: 0x100003B18, symSize: 0x48 }
  - { offset: 0x541B, size: 0x8, addend: 0x0, symName: __Z3popP5Stack, symObjAddr: 0x1C4, symBinAddr: 0x100003A8C, symSize: 0x8C }
  - { offset: 0x545E, size: 0x8, addend: 0x0, symName: __Z4pushP5Stacki, symObjAddr: 0x12C, symBinAddr: 0x1000039F4, symSize: 0x98 }
  - { offset: 0x549B, size: 0x8, addend: 0x0, symName: __Z7display5Stack, symObjAddr: 0x8C, symBinAddr: 0x100003954, symSize: 0xA0 }
  - { offset: 0x54EA, size: 0x8, addend: 0x0, symName: __Z6createP5Stack, symObjAddr: 0x0, symBinAddr: 0x1000038C8, symSize: 0x8C }
...
